blank_issues_enabled: false
contact_links:
  - name: Ask A Question
    url: https://github.com/Carltoffel/tmux-solarized/discussions/new?category=q-a
    about: Need help tweaking your Solarized tmux configuration? Ask questions in GitHub Discussions!
  - name: Show & Tell
    url: https://github.com/Carltoffel/tmux-solarized/discussions/new?category=show-tell
    about: Want to showcase your customised Solarized tmux configuration? Show it off in GitHub Discussions!
